### ISSUE TITLE
Muxing only works the first time after opening the program

### ISSUE THREAD

**Issue by Arjak89** [TrekkiesUnite118/SegaSaturnFilmMuxer#1]
When trying to mux my custom English CPKs with the original Japanese video, the results are a glitchy mess, showing stills from different scenes and with garbled skipping audio. The frame counts are exactly the same between the CPKs, but they won't mux together. I am using Version 1.1.0.

EDIT: I have discovered that the problem is not file compatibility, but the program. The first video you mux after opening the program works perfectly, but every subsequent video doesn't compile correctly unless you first exit the program and restart it.

**Comment by TrekkiesUnite118** [comment]
This should be fixed with release 2.0.
